using VoltManager.Models;

namespace VoltManager.Bridge.Handlers;

public sealed record EnergyRpcActions(
    Func<object> GetBatteryHealth,
    Func<object> GetBatteryPower,
    Func<IReadOnlyList<BatteryHistorySample>> GetBatteryHistory,
    Func<object> GetDisplayBrightness,
    Func<int, object> SetDisplayBrightness,
    Func<(bool allPresent, List<PlanId> missing)> CheckDefaultPlans,
    Func<bool> RestoreDefaultPlans,
    Func<ExtraPlansReport> FindExtraPlans,
    Func<IReadOnlyCollection<string>, DeleteExtraPlansResult> DeleteExtraPlans,
    Action<IEnumerable<string>> DismissExtraPlans,
    Func<object?> GetActivePlan,
    Func<object> GetActivePlanReason,
    Func<object> GetPlanHistory,
    Func<long> ClearPlanHistory,
    Func<object> ListPowerPlans,
    Func<object> GetKeepAwakeState,
    Func<bool, object> SetKeepAwake,
    Func<bool, int, object> SetKeepAwakeSafety,
    Func<object> GetCpuAutomationState,
    Func<PlanId, TimeSpan?, bool> SetManualOverride,
    Action ClearManualOverride,
    Func<object?> GetManualOverride,
    Func<object> GetPowerSourcePlanState,
    Func<bool, object> SetPowerSourcePlanSwitch,
    Func<object> GetThermalGuardState,
    Func<bool, object> SetThermalGuardEnabled,
    Func<ThermalGuardSettings, object> SetThermalGuardSettings,
    Func<object> GetIdlePowerGuardState,
    Func<bool, object> SetIdlePowerGuardEnabled,
    Func<IdlePowerGuardSettings, object> SetIdlePowerGuardSettings,
    Func<object> GetScheduledPowerAction,
    Action<ScheduledPowerActionType> ExecutePowerAction,
    Func<TimeSpan, ScheduledPowerActionType, object> ScheduleAfter,
    Func<TimeOnly, ScheduledPowerActionType, object> ScheduleDaily,
    Func<object> CancelScheduledPowerAction,
    Func<string?, object> GetPlanTimeouts,
    Func<string?, object> GetPlanParameters,
    Func<string, string, int, int, bool> SetPlanParameter,
    Func<DateTime> UtcNow);
