module.exports = {
  darkMode: "class",
  content: [
    "../src/VoltManager/wwwroot/index.html",
    "../src/VoltManager/wwwroot/js/*.js",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#232f50",
        "surface-container": "#122131",
        "secondary-fixed": "#74f5ff",
        "on-tertiary-fixed": "#0d1a39",
        "on-secondary": "#00363a",
        "secondary-container": "#00f1fe",
        "surface-container-high": "#1c2b3c",
        "on-surface": "#d4e4fa",
        "tertiary-fixed": "#dae2ff",
        "tertiary-container": "#031030",
        "outline-variant": "#46464d",
        "on-error-container": "#ffdad6",
        "secondary": "#ddfcff",
        "error": "#ffb4ab",
        "primary-container": "#0a1128",
        "background": "#051424",
        "on-secondary-fixed": "#002022",
        "surface-container-lowest": "#010f1f",
        "on-primary-container": "#767c99",
        "error-container": "#93000a",
        "inverse-on-surface": "#233143",
        "surface-variant": "#273647",
        "on-primary-fixed": "#141a32",
        "primary-fixed-dim": "#bfc5e4",
        "surface-container-highest": "#273647",
        "on-primary-fixed-variant": "#3f465f",
        "secondary-fixed-dim": "#00dbe7",
        "on-background": "#d4e4fa",
        "on-secondary-container": "#006a70",
        "surface-container-low": "#0d1c2d",
        "tertiary-fixed-dim": "#bac5ee",
        "on-secondary-fixed-variant": "#004f54",
        "surface-bright": "#2c3a4c",
        "primary": "#bfc5e4",
        "on-error": "#690005",
        "inverse-primary": "#575d78",
        "surface": "#051424",
        "outline": "#909098",
        "on-tertiary-fixed-variant": "#3a4667",
        "inverse-surface": "#d4e4fa",
        "primary-fixed": "#dce1ff",
        "tertiary": "#bac5ee",
        "on-surface-variant": "#c6c6ce",
        "on-tertiary-container": "#717ca1",
        "on-primary": "#292f48",
        "surface-tint": "#bfc5e4",
        "surface-dim": "#051424",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "16px",
        xs: "4px",
        gutter: "16px",
        unit: "4px",
        sm: "8px",
        xl: "32px",
        "margin-page": "24px",
        lg: "24px",
      },
      fontSize: {
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.1em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
